using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace HISA.EVEData;

internal static class IntelShipClassOverrides
{
    internal static IReadOnlyDictionary<string, IntelShipClass> ByShipName { get; } = Build();

    private static IReadOnlyDictionary<string, IntelShipClass> Build()
    {
        Dictionary<string, IntelShipClass> map = new Dictionary<string, IntelShipClass>(StringComparer.OrdinalIgnoreCase);

        try
        {
            JObject root = JObject.Parse(ShipHullClassJson);
            foreach(JProperty hull in root.Properties())
            {
                IntelShipClass shipClass = MapHullGroupToClass(hull.Name);
                if(hull.Value is not JArray names)
                {
                    continue;
                }

                foreach(JToken token in names)
                {
                    string shipName = token?.ToString()?.Trim();
                    if(string.IsNullOrWhiteSpace(shipName) || map.ContainsKey(shipName))
                    {
                        continue;
                    }

                    map[shipName] = shipClass;
                }
            }
        }
        catch
        {
            // Fall back to static-data parsing + keyword heuristics if overrides cannot be parsed.
        }

        return map;
    }

    private static IntelShipClass MapHullGroupToClass(string hullGroup)
    {
        return hullGroup switch
        {
            "Capsule" => IntelShipClass.Capsule,
            "Corvette" => IntelShipClass.Corvette,
            "Shuttle" => IntelShipClass.Shuttle,
            "Frigate" => IntelShipClass.Frigate,
            "Destroyer" => IntelShipClass.Destroyer,
            "Cruiser" => IntelShipClass.Cruiser,
            "Battlecruiser" => IntelShipClass.Battlecruiser,
            "Battleship" => IntelShipClass.Battleship,
            "Industrial" => IntelShipClass.Industrial,
            "Mining Barge" => IntelShipClass.Mining,
            "Freighter" => IntelShipClass.Freighter,
            "Capital Industrial" => IntelShipClass.Capital,
            "Dreadnought" => IntelShipClass.Capital,
            "Carrier" => IntelShipClass.Capital,
            "Force Auxiliary" => IntelShipClass.Capital,
            "Supercarrier" => IntelShipClass.Capital,
            "Titan" => IntelShipClass.Capital,
            _ => IntelShipClass.UnknownHostile
        };
    }

    private const string ShipHullClassJson = """
{
  "Capsule": [
    "Capsule"
  ],
  "Corvette": [
    "Echo",
    "Hematos",
    "Ibis",
    "Immolator",
    "Impairor",
    "Reaper",
    "Taipan",
    "Velator",
    "Violator"
  ],
  "Shuttle": [
    "Amarr Shuttle",
    "Apotheosis",
    "Boobook",
    "Caldari Shuttle",
    "Civilian Amarr Shuttle",
    "Civilian Caldari Shuttle",
    "Civilian Gallente Shuttle",
    "Civilian Minmatar Shuttle",
    "Council Diplomatic Shuttle",
    "Gallente Shuttle",
    "Goru's Shuttle",
    "Guristas Shuttle",
    "InterBus Shuttle",
    "Leopard",
    "Minmatar Shuttle"
  ],
  "Frigate": [
    "Ares",
    "Astero",
    "Atron",
    "Bantam",
    "Breacher",
    "Burst",
    "Buzzard",
    "Caldari Navy Hookbill",
    "Caedes",
    "Cambion",
    "Cheetah",
    "Chremoas",
    "Claw",
    "Condor",
    "Crucifier",
    "Crucifier Navy Issue",
    "Cruor",
    "Crusader",
    "Daredevil",
    "Damavik",
    "Deacon",
    "Dramiel",
    "Enyo",
    "Executioner",
    "Federation Navy Comet",
    "Firetail",
    "Freki",
    "Garmur",
    "Geri",
    "Gold Magnate",
    "Griffin",
    "Griffin Navy Issue",
    "Harpy",
    "Hawk",
    "Helios",
    "Heron",
    "Heron Navy Issue",
    "Hound",
    "Hydra",
    "Hyena",
    "Imicus",
    "Imicus Navy Issue",
    "Imp",
    "Imperial Navy Slicer",
    "Incursus",
    "Inquisitor",
    "Ishkur",
    "Jaguar",
    "Kestrel",
    "Kikimora",
    "Kirin",
    "Kitsune",
    "Magnate",
    "Magnate Navy Issue",
    "Malice",
    "Malediction",
    "Maulus",
    "Maulus Navy Issue",
    "Metamorphosis",
    "Navitas",
    "Nergal",
    "Nemesis",
    "Pacifier",
    "Probe",
    "Probe Fleet Issue",
    "Punisher",
    "Raptor",
    "Republic Fleet Firetail",
    "Retribution",
    "Rifter",
    "Slasher",
    "Succubus",
    "Sukuuvestaa Heron",
    "Taranis",
    "Tash-Murkon Magnate",
    "Tormentor",
    "Tristan",
    "Utu",
    "Vengeance",
    "Venture",
    "Vherokior Probe",
    "Vigil",
    "Vigil Fleet Issue",
    "Whiptail",
    "Wolf",
    "Worm",
    "Wraith",
    "Zephyr"
  ],
  "Destroyer": [
    "Algos",
    "Bifrost",
    "Catalyst",
    "Catalyst Navy Issue",
    "Coercer",
    "Coercer Navy Issue",
    "Confessor",
    "Corax",
    "Cormorant",
    "Cormorant Navy Issue",
    "Dragoon",
    "Draugur",
    "Eris",
    "Flycatcher",
    "Heretic",
    "Hecate",
    "Inner Zone Shipping Catalyst",
    "Intaki Syndicate Catalyst",
    "InterBus Catalyst",
    "Jackdaw",
    "Magus",
    "Mamba",
    "Mekubal",
    "Nefantar Thrasher",
    "Nergal",
    "Pontifex",
    "Sabre",
    "Sunesis",
    "Svipul",
    "Talwar",
    "Tholos",
    "Thrasher",
    "Thrasher Fleet Issue",
    "Thrasher Tribal Issue"
  ],
  "Cruiser": [
    "Arbitrator",
    "Ashimmu",
    "Augoror",
    "Augoror Navy Issue",
    "Bellicose",
    "Blackbird",
    "Broadsword",
    "Caracal",
    "Caracal Navy Issue",
    "Celestis",
    "Cerberus",
    "Cynabal",
    "Curse",
    "Deimos",
    "Devoter",
    "Enforcer",
    "Exequror",
    "Exequror Navy Issue",
    "Falcon",
    "Fiend",
    "Gila",
    "Guardian-Vexor",
    "Huginn",
    "Ishtar",
    "Ixion",
    "Laelaps",
    "Lachesis",
    "Legion",
    "Loki",
    "Maller",
    "Monitor",
    "Moa",
    "Muninn",
    "Omen",
    "Omen Navy Issue",
    "Orthrus",
    "Phantasm",
    "Phobos",
    "Pilgrim",
    "Proteus",
    "Rapier",
    "Rodiva",
    "Rook",
    "Rupture",
    "Scythe",
    "Scythe Fleet Issue",
    "Stratios",
    "Stratios Emergency Responder",
    "Stabber",
    "Stabber Fleet Issue",
    "Stormbringer",
    "Tengu",
    "Tiamat",
    "Thorax",
    "Vedmak",
    "Vexor",
    "Vexor Navy Issue",
    "Victor",
    "Victorieux Luxury Yacht",
    "Vigilant",
    "Zealot",
    "Zarmazd"
  ],
  "Battlecruiser": [
    "Absolution",
    "Alligator",
    "Astarte",
    "Brutix",
    "Brutix Navy Issue",
    "Cenotaph",
    "Claymore",
    "Damnation",
    "Drake",
    "Drake Navy Issue",
    "Eos",
    "Ferox",
    "Ferox Navy Issue",
    "Gnosis",
    "Harbinger",
    "Harbinger Navy Issue",
    "Hurricane",
    "Hurricane Fleet Issue",
    "Khizriel",
    "Myrmidon",
    "Myrmidon Navy Issue",
    "Naga",
    "Oracle",
    "Prophecy",
    "Prophecy Navy Issue",
    "Sleipnir",
    "Talos",
    "Tornado",
    "Vulture"
  ],
  "Battleship": [
    "Abaddon",
    "Apocalypse",
    "Apocalypse Imperial Issue",
    "Apocalypse Navy Issue",
    "Armageddon",
    "Armageddon Imperial Issue",
    "Armageddon Navy Issue",
    "Barghest",
    "Bhaalgorn",
    "Cobra",
    "Dominix",
    "Dominix Navy Issue",
    "Eidolon",
    "Golem",
    "Hyperion",
    "Kronos",
    "Leshak",
    "Machariel",
    "Maelstrom",
    "Maelstrom Fleet Issue",
    "Marshal",
    "Megathron",
    "Megathron Federate Issue",
    "Megathron Navy Issue",
    "Nestor",
    "Nightmare",
    "Paladin",
    "Panther",
    "Praxis",
    "Python",
    "Rattlesnake",
    "Rattlesnake Victory Edition",
    "Raven",
    "Raven Navy Issue",
    "Raven State Issue",
    "Redeemer",
    "Rokh",
    "Scorpion",
    "Sin",
    "Tempest",
    "Tempest Fleet Issue",
    "Tempest Tribal Issue",
    "Thunderchild",
    "Typhoon",
    "Typhoon Fleet Issue",
    "Vargur",
    "Vindicator",
    "Widow"
  ],
  "Industrial": [
    "Badger",
    "Bestower",
    "Bustard",
    "Crane",
    "Deluge",
    "Epithal",
    "Hoarder",
    "Impel",
    "Iteron Mark V",
    "Kryos",
    "Mammoth",
    "Mastodon",
    "Miasmos",
    "Miasmos Amastris Edition",
    "Miasmos Quafe Ultra Edition",
    "Miasmos Quafe Ultramarine Edition",
    "Nereus",
    "Porpoise",
    "Primae",
    "Prorator",
    "Prowler",
    "Sigil",
    "Tayra",
    "Torrent",
    "Viator",
    "Visitant",
    "Wreathe"
  ],
  "Mining Barge": [
    "Covetor",
    "Endurance",
    "Hulk",
    "Mackinaw",
    "Procurer",
    "Prospect",
    "Retriever",
    "Skiff"
  ],
  "Freighter": [
    "Anshar",
    "Ark",
    "Avalanche",
    "Bowhead",
    "Charon",
    "Fenrir",
    "Providence",
    "Rhea"
  ],
  "Capital Industrial": [
    "Loggerhead",
    "Orca",
    "Rorqual"
  ],
  "Dreadnought": [
    "Bane",
    "Caiman",
    "Chemosh",
    "Hubris",
    "Karura",
    "Moros",
    "Moros Navy Issue",
    "Naglfar",
    "Naglfar Fleet Issue",
    "Phoenix",
    "Phoenix Navy Issue",
    "Revelation",
    "Revelation Navy Issue",
    "Valravn",
    "Vehement",
    "Zirnitra"
  ],
  "Carrier": [
    "Archon",
    "Chimera",
    "Nidhoggur",
    "Thanatos"
  ],
  "Force Auxiliary": [
    "Apostle",
    "Dagon",
    "Lif",
    "Minokawa"
  ],
  "Supercarrier": [
    "Aeon",
    "Hel",
    "Nyx",
    "Revenant",
    "Vendetta",
    "Wyvern"
  ],
  "Titan": [
    "Avatar",
    "Azariel",
    "Erebus",
    "Komodo",
    "Leviathan",
    "Molok",
    "Ragnarok",
    "Vanquisher"
  ]
}
""";
}
